apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-clickhouse-access
  namespace: clickhouse
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-clickhouse-binding
  namespace: clickhouse
subjects:
  - kind: ServiceAccount
    name: prometheus-stack-kube-prom-prometheus
    namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-clickhouse-access
  apiGroup: rbac.authorization.k8s.io
