#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: Retrieve a license from your Teleport account https://teleport.sh
#     if you are an Enterprise customer.
#
version: v3
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ''
  diag_addr: ''
auth_service:
  enabled: 'yes'
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: 'no'
proxy_service:
  enabled: 'yes'
  public_addr: 'localhost' # Should be your public addr
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
