version: '2'

services:
  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami
    ports:
      - 2379:2379
      - 2380:2380

volumes:
  etcd_data:
    driver: local
