kind: role
version: v7
metadata:
  name: member
spec:
  allow:
    kubernetes_groups: ['system:masters']
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: '*'
        namespace: '*'
        name: '*'
        verbs: ['*']
