apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-gcs-test
spec:
  template:
    spec:
      containers:
        - name: writer
          image: busybox
          command:
            - sleep
            - infinity
          volumeMounts:
            - name: csi-gcs-pvc-1
              mountPath: /data1
            - name: csi-gcs-pvc-2
              mountPath: /data2
     volumes:
        - name: csi-gcs-pvc-1
          persistentVolumeClaim:
            claimName: csi-gcs-pvc-1
        - name: csi-gcs-pvc-2
          persistentVolumeClaim:
            claimName: csi-gcs-pvc-2
