apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-pvc-1
  annotations:
    gcs.csi.ofek.dev/bucket: csigcstest1
spec:
  storageClassName: csi-gcs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-pvc-2
  annotations:
    gcs.csi.ofek.dev/bucket: csigcstest2
spec:
  storageClassName: csi-gcs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
