apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
  annotations:
    prometheus.io/port: "7000"
    prometheus.io/scrape: "true"
spec:
  configuration:
    clusters:
      - name: chk01
        layout:
          replicasCount: 3
        templates:
          podTemplate: keeper-pod-template
          volumeClaimTemplate: keeper-storage-template
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"

  templates:
    podTemplates:
      - name: keeper-pod-template
        metadata:
          labels:
            app: clickhouse-keeper
          annotations:
            prometheus.io/port: "7000"
            prometheus.io/scrape: "true"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - clickhouse-keeper
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: clickhouse-keeper
              image: clickhouse/clickhouse-keeper:25.8
              ports:
                - name: tcp
                  containerPort: 9181
                - name: metrics
                  containerPort: 7000
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: "1Gi"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage-template
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: openebs-lvmpv
          resources:
            requests:
              storage: 1Gi
