apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: cluster01
  namespace: clickhouse
spec:
  configuration:
    zookeeper:
      nodes:
        - host: keeper-clickhouse-keeper.clickhouse.svc.cluster.local
          port: 2181

    clusters:
      - name: cluster01
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-pod-template
          volumeClaimTemplate: clickhouse-pvc-template
    settings:
      # to allow scrape metrics via embedded prometheus protocol
      prometheus/endpoint: /metrics
      prometheus/port: 8888
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
      prometheus/status_info: true

  templates:
    podTemplates:
      - name: clickhouse-pod-template
        metadata:
          # for `additionalScrapeConfigs`, look https://github.com/Altinity/clickhouse-operator/blob/master/deploy/prometheus/prometheus-template.yaml#L11
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "8888"
        spec:
          # affinity:
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       - labelSelector:
          #           matchExpressions:
          #             - key: clickhouse.altinity.com/chi
          #               operator: In
          #               values:
          #                 - clickhouse
          #         topologyKey: kubernetes.io/hostname
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.8
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
              env:
                - name: CLICKHOUSE_MAX_THREADS
                  value: "2"
              # for `PodMonitor`
              ports:
                - name: "metrics"
                  containerPort: 8888

    volumeClaimTemplates:
      - name: clickhouse-pvc-template
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: openebs-lvmpv
          resources:
            requests:
              storage: 10Gi
