apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: chk01
        layout:
          replicasCount: 3
        templates:
          podTemplate: keeper-pod-template
          volumeClaimTemplate: keeper-storage-template

  templates:
    podTemplates:
      - name: keeper-pod-template
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - clickhouse-keeper
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: clickhouse-keeper
              image: clickhouse/clickhouse-keeper:25.8
              ports:
                - name: tcp
                  containerPort: 9181
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: "1Gi"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: keeper-storage-template
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: 10Gi
