---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-metrics
  namespace: clickhouse
  labels:
    app: clickhouse
    clickhouse.altinity.com/chi: cluster01
spec:
  selector:
    clickhouse.altinity.com/chi: cluster01
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper-metrics
  namespace: clickhouse
  labels:
    app: clickhouse-keeper
    clickhouse-keeper.altinity.com/chk: clickhouse-keeper
spec:
  selector:
    clickhouse-keeper.altinity.com/chk: clickhouse-keeper
  ports:
    - name: metrics
      port: 7000
      targetPort: 7000
      protocol: TCP
  type: ClusterIP
