apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: cluster01
  namespace: clickhouse
spec:
  configuration:
    zookeeper:
      nodes:
        - host: keeper-clickhouse-keeper.clickhouse.svc.cluster.local
          port: 2181

    clusters:
      - name: cluster01
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-pod-template
          volumeClaimTemplate: clickhouse-pvc-template

  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          # affinity:
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       - labelSelector:
          #           matchExpressions:
          #             - key: clickhouse.altinity.com/chi
          #               operator: In
          #               values:
          #                 - clickhouse
          #         topologyKey: kubernetes.io/hostname
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.8
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
              env:
                - name: CLICKHOUSE_MAX_THREADS
                  value: "2"

    volumeClaimTemplates:
      - name: clickhouse-pvc-template
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: 50Gi
