[package]
name = "iroh-tour"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
iroh = { version = "0.91.0", features = ["discovery-local-network"] }
iroh-blobs = "0.93.0"
iroh-gossip = "0.91.0"
rand = "0.9.2"
tokio = "1.47.0"
