version: '3.7'

services:
  minio:
    restart: always
    image: minio/minio:latest
    container_name: minio
    # environment:
      # MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3-data:/data
    entrypoint: minio server /data --console-address ":9001"
  minio_mc:
    image: minio/mc:latest
    container_name: minio_mc
    volumes:
      - ./cors.xml:/tmp/cors.xml
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rb --force local/test-bucket/;
      /usr/bin/mc mb --quiet local/test-bucket/;
      /usr/bin/mc policy set public local/test-bucket;
      /usr/bin/mc admin config export local/test-bucket;
      /usr/bin/mc admin config set local/test-bucket api 'cors_allow_origin=minio';
      /usr/bin/mc admin config get local/test-bucket api;
      "

volumes:
  s3-data:
