apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-objstore
  namespace: monitoring
stringData:
  objstore.yml: |-
    type: s3
    config:
      bucket: thanos
      endpoint: thanos-minio.monitoring:9000
      access_key: admin
      secret_key: p@ssw0rd!
      insecure: true
