version: '3.1'

volumes:
  guacd_data:

services:
  casvisor:
    image: casbin/casvisor:v1.66.0
    container_name: casvisor
    restart: always
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - '19000:19000'
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: 'true'
    volumes:
      - ./casvisorconf/app.conf:/home/casvisor/conf/app.conf

  casdoor:
    image: casbin/casdoor:v1.794.0
    container_name: casdoor
    restart: always
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: 'true'
    volumes:
      - ./casdoorconf/app.conf:/home/casdoor/conf/app.conf

  db:
    restart: always
    image: mysql:8.0.25
    container_name: mysql
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    environment:
      GUACD_LOG_LEVEL: debug
    volumes:
      - guacd_data:/usr/local/casvisor/data
    ports:
      - '4822:4822'
    restart: always
