apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pvc
  annotations:
    gcs.csi.ofek.dev/bucket: fileserver
spec:
  storageClassName: csi-gcs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
