apiVersion: v1
kind: Service
metadata:
  name: csi-gcs-fileserver
  labels:
    app: csi-gcs-fileserver
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: csi-gcs-fileserver
